config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pets#index"
  resources :pets
  resources :users, only: [:indes, :show]

  get 'last_five', to: 'pets#five_last_pets'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :species, inclusion: {in: %w(dog cat fish turtle rabbit bird)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new, status: 422
    end
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit, status: 422
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  def five_last_pets
    @pets = Pet.all.last(5)
  end


  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for pet do |f| %>
  <%= f.input :name, required: true %>
  <%= f.input :address %>
  <%= f.input :species %>
  <%= f.input :found_on %>
  <%= f.submit %>
<% end %>

app/views/pets/create.html.erb
<h1>Pets#create</h1>
<p>Find me in app/views/pets/create.html.erb</p>

app/views/pets/destroy.html.erb
<h1>Pets#destroy</h1>
<p>Find me in app/views/pets/destroy.html.erb</p>

app/views/pets/edit.html.erb
<div class="container">
  <h1>Editar <%= @pet.name%> </h1>
  <%= render "form", pet: @pet %>
</div>

app/views/pets/five_last_pets.html.erb
<h1>Ultimos 5</h1>

app/views/pets/index.html.erb
<div class="container">

  <h1>Todos os pets encontrados</h1>

  <ul>
    <% @pets.each do |pet| %>
      <div class="my-3">
        <li class=""><%= pet.name %></li>
        <%= link_to "Ver detalhes", pet_path(pet) %>
      </div>
    <% end %>
  </ul>


  <%= link_to "Cadastrar Pet", new_pet_path, class: "btn btn-primary" %>
  <%= link_to "Ultimos 5", last_five_path, class: "btn btn-primary" %>

</div>

app/views/pets/new.html.erb
<div class="container">
  <h1>Cadastrar pet encontrado</h1>
  <%= render "form", pet: @pet %>
</div>

app/views/pets/show.html.erb
<div class="container">
  <h1>Detalhes do <%= @pet.name %></h1>
  <p>Encontrado ha <%= (Date.today - @pet.found_on).to_i %> dias</p>
  <p>O(A) <%= @pet.name %> da spécie <%= @pet.species %> foi encontrado em <%= @pet.address %> no dia <%= @pet.found_on %></p>
  <%= link_to "Editar Pet", edit_pet_path, class: "btn btn-primary" %>
  <%= link_to "Deletar", pet_path(@pet), class: "btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Tem certeza disso?"} %>
</div>

app/views/pets/update.html.erb
<h1>Pets#update</h1>
<p>Find me in app/views/pets/update.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>